release-drafter/release-drafter

lib/releases.js

Use correct author of pull request

---

README.md

Document usage of Probot Config repo

---

Dockerfile

Renovate bot will then give nicer update PRs

Switch to using the full version in the Docker tag

---

README.md
index.js
lib/releases.js
lib/versions.js
package.json
test/fixtures/config-with-next-versioning.yml
test/index.test.js
test/versions.test.js
yarn.lock

Automatic next release naming

---

package.json

Otherwise it will not pass setup process.

Update repo to complete url

---

README.md

Fix example change template format

---

.eslintignore
.eslintrc
.vscode/extensions.json
.vscode/settings.json
package.json
test/.eslintrc
yarn.lock

I've added an ESLint config to catch common mistakes such as an undefined variable. It's also integrated with `lint-staged` so that code with linting errors can't be commited. I've tried to make sure no unnecessary rules have been turned on to prevent frustration. I added this purely to catch mistakes like missing imports and undefined variables :)

Add ESLint config

---

README.md
index.js
lib/releases.js
lib/template.js
lib/versions.js
package.json
test/fixtures/config/config-with-major-minor-patch-version-template.yml
test/fixtures/config/config-with-major-minor-version-template.yml
test/fixtures/config/config-with-major-version-template.yml
test/index.test.js
test/template.test.js
test/versions.test.js

fixes #156 
supersedes #158 
I don't know if makes sense to support version template replacement inside the body/tag/name :confused: 
Also in doubt about the readme :sweat:
Please take a look @toolmantim and @TimonVS

add support for version-template

---

package.json

in addition to #121
Just helping you out @toolmantim when you made the release :package:

fix open-releases

---

README.md

This will help to avoid the most common misconfiguration mistake: special characters in some of the configuration values.

String quote example config string values

---

bin/generate-fixtures.js
lib/commits.js
package.json
test/fixtures/__generated__/README.md
test/fixtures/__generated__/graphql-commits-merge-commit.json
test/fixtures/__generated__/graphql-commits-rebase-merging.json
test/fixtures/__generated__/graphql-commits-squash-merging.json
test/index.test.js
yarn.lock

Add a filter function to filter cross repository PRs, I also added a script to be able te regenerate some of the fixtures.
Fixes #221
Fixes #217

Filter cross repository PRs

---

README.md
lib/releases.js
test/fixtures/config/config-with-categories-2.yml
test/index.test.js

Support specifying multiple labels for each category

---

app.yml

This makes it easier to deploy using probot cli as it includes the permissions and events required.

Added a GitHub App Manifest to help those deploying this app

---

README.md

no reverse wording of update release draft.
Let's call it release drafter instead of release management

More readable release drafter yml example

---

lib/releases.js

Fixes: https://github.com/toolmantim/release-drafter/issues/301
To try: `uses: oleg-nenashev/jenkins-release-drafter@v5.2.0-jenkins-4` can be used to try it out for GitHub Actions users

Prevent crash when a pull request author is deleted

---

index.js
lib/config.js
test/config.test.js

I put all things related to config in a separate module to make the entry file of the app more readable. I've also added tests to make sure it works as intended.

Put config in seperate module

---

README.md
index.js

I extracted some duplicate code for the Action outputs to a single function to make the code more readable and added documentation for the Action outputs.

Add documentation for Action outputs

---

.github/workflows/tests.yml

tests are not running on a PR 😱

Run tests on pull requests

---

bin/generate-schema.js
index.js
lib/config.js
lib/default-config.js
lib/log.js
lib/releases.js
lib/schema.js
lib/sort-pull-requests.js
package.json
schema.json
test/config.test.js
test/fixtures/config/config-with-schema-error.yml
test/fixtures/config/config-with-yaml-exception.yml
test/index.test.js
test/schema.test.js
yarn.lock

The schema works. Tests are passing.
@toolmantim @TimonVS feel free to add your suggestions
fixes #353

Improve config validation using a Joi schema

---

lib/config.js
lib/schema.js
lib/utils.js
package.json
test/schema.test.js
yarn.lock

Implemented some improvements to the config schema validation from #193:
- Set Action status to failed if an invalid config is supplied
- Make schema validation more forgiving by allowing unknown properties
- Log JSON representation of config with error annotations

Config schema validation improvements

---

index.js
lib/config.js
package.json
test/config.test.js
yarn.lock

now probot config has more context and should hopefully understand branching.
~potentially fixes #398~

use context.config to load the config

---

.vscode/launch.json

useful when wanting to run a single it or describe block by selecting the text and pressing f5

Add VS Code task to run selected test

---

.github/workflows/tests.yml
bin/generate-fixtures.js
lib/releases.js
lib/schema.js
package.json
test/fixtures/__generated__/graphql-commits-overlapping-label.json
test/fixtures/config/config-with-categories-3.yml
test/fixtures/config/config-with-categories-4.yml
test/index.test.js

resolves #293
resolves #403
This should fix categorization overlapping. I'd like to have someone review the code around the looping. Wonder if we could optimize the looping.
I'd like to avoid using `reduce` as I feel it makes this area of the code particular hard to read 😅

Fix overlapping label categorization

---

test/index.test.js

I forked to debug an issue, but thought I might as well submit this unrelated correction separately.

Fixing test description typo

---

index.js
test/index.test.js

This adds body reply so when `setOutput` is hit they actually have something to output

fix setOutput

---

bin/generate-fixtures.js
bin/generate-schema.js
index.js
lib/base64.js
lib/commits.js
lib/config.js
lib/default-config.js
lib/pagination.js
lib/releases.js
lib/schema.js
lib/sort-pull-requests.js
lib/template.js
lib/triggerable-branch.js
lib/versions.js
test/config.test.js
test/helpers/config-mock.js
test/index.test.js
test/pagination.test.js
test/schema.test.js
test/template.test.js
test/versions.test.js

v2 of prettier changed the default styling.

fix eslint/prettier styling

---

README.md
index.js

This PR resolves the issue #461 
I didn't add any tests and checks (if), because looking overall the code I couldn't find any scenario where the body couldn't exist.

Add generated release body on output

---

test/index.test.js

`yarn test -u` or `yarn test --updateSnapshot` to update snapshots, more maintainable tests 😆

use `toMatchInlineSnapshot`

---

lib/commits.js
test/fixtures/__generated__/graphql-commits-forking.json
test/fixtures/__generated__/graphql-commits-merge-commit.json
test/fixtures/__generated__/graphql-commits-overlapping-label.json
test/fixtures/__generated__/graphql-commits-rebase-merging.json
test/fixtures/__generated__/graphql-commits-squash-merging.json
test/fixtures/graphql-commits-empty.json
test/fixtures/graphql-commits-no-prs.json
test/fixtures/graphql-commits-paginated-1.json
test/fixtures/graphql-commits-paginated-2.json
test/pagination.test.js

fixes #578
fixes #615
Tested in https://github.com/timja/dummy-repo-drafter/releases
cc @jetersen

Annotated tags support when publishing

---

index.js
lib/releases.js

Reverts release-drafter/release-drafter#657
@fujifish

Revert "filter releases to consider only the target branch "

---

README.md

fix(readme): replace version resolution with version resolver

---

README.md

Reverts release-drafter/release-drafter#711

Revert "Improve example to use default branch"

---

README.md

Resolves https://github.com/release-drafter/release-drafter/issues/835

Docs: Clarify config must be on default branch

---

index.js

Fix TypeError when autolabeler body reqex is set and PR body is null/empty (#968)

Check if PR body is null

---

README.md

See https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target.

Provide autolabeler configuration for forks

---

schema.json

fixes https://github.com/release-drafter/release-drafter/issues/971

Add commitish configuration option to schema.json

---

index.js

Support `pull_request_target` events

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Helps setup dev container with nodejs

add dev container

---

schema.json

Missed a step in the merge process

Regenerate schema after #1084

---

README.md

Fixes #869
Closes #870
Permissions based on analysis by https://app.stepsecurity.io/.

Add permissions to README

---

README.md

Hello!
The Vercel link was left as Now, so I fixed it.

Fix Vercel link

---

.github/workflows/release.yml
package.json
yarn.lock

Fixes https://github.com/release-drafter/release-drafter/issues/1246
cc https://github.com/jenkins-infra/helpdesk/issues/3176 for internal reference.

Address `set-output` deprecation

---

README.md

I have always used this tool.
Thank you very much.
Since version 6 was released, the README .md was also modified.
https://github.com/release-drafter/release-drafter/releases/tag/v6.0.0

Update v6 README.md

---

CONTRIBUTING.md

I noticed the fork link is broken, so I fixed it :)
Some grammar fixes.

docs: Fix Fork Link
