release-drafter/release-drafter

lib/triggerable-branch.js
Fixes `errorvalidBranches.join is not a function` errors, for configs such as the [following](https://github.com/custom-components/information/blob/master/.github/release-drafter.yml):
```yml
branches: dev
template: |
$CHANGES
```
=> Don't error for non-array branches

lib/commits.js, test/commits.test.js
When a PR is squashed and merged, the commit message will contain multiple lines:
```
<PR TITLE> (#<PR NUMBER>)
<FIRST COMMIT MESSAGE>
<SECOND COMMIT MESSAGE>
etc
```
When we were extracting PR numbers, we were matching against a commit message ending in ` (#1234)`. However, we should have looked at the first line of a commit message ending in that.
Fixes #29
=> Fix extracting commit numbers

README.md, index.js, lib/releases.js, lib/triggerable-branch.js, test/fixtures/config-with-changes-templates.yml, test/index.test.js
As requested in #35, this adds new `change-template` and `no-changes-template` configuration variables so you can completely customize the format for the release body.
=> Add the ability to customize each change line

README.md, index.js, lib/releases.js, test/fixtures/commits.json, test/fixtures/config-with-contributors.yml, test/index.test.js
This adds a `$CONTRIBUTORS` template variable, which is a comma separated list of GitHub usernames from the commit authors, commit commiters, and pull request authors.
For example:
```yml
template: |
❤️ A big thanks to $CONTRIBUTORS
```
which would produce:
```md
❤️ A big thanks to @bkeepers, @salmanulfarzy and @toolmantim.
```
Fixes #53
=> Add a $CONTRIBUTORS template variable

README.md
The `change-template` specified in the README was missing the `#` which is present in the code. Oops!
=> Correct default `change-template` in the README

.prettierrc, .vscode/settings.json, CODE_OF_CONDUCT.md, README.md, lib/base64.js, lib/commits.js, lib/releases.js, lib/triggerable-branch.js, package.json, test/commits.test.js, test/index.test.js, yarn.lock
While working on this awesome tool I was really missing auto formatting. In this PR I've added Prettier and I added a pre-commit hook so that all commits will be consistently formatted. I also removed `standard` as it clashes with the formatting of Prettier, if desired I can add back `standard` by utilizing `eslint-config-prettier` which will disable all rules that clash with Prettier.
Let me know if you'd like me to change anything to suit your needs best :)
If you intend to merge this PR you can run `yarn prettier` afterwards to format all existing files.
=> Add Prettier

index.js, lib/releases.js, package.json, test/index.test.js, yarn.lock
Refactor usage of deprecated APIs to make Release Drafter compatible with Probot v9 (ref: https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations).
=> Refactor usage of deprecated APIs

lib/commits.js, test/index.test.js
I missed the deprecated `getCommits` in #143.
=> Update deprecated getCommits to listCommits

.gitignore
prevents anyone from accidentally committing the `package-lock.json` on a yarn project.
See https://github.com/toolmantim/release-drafter/pull/158#discussion_r271242287
=> add package lock to gitignore

README.md
I added links to PR Labeler and Probot Auto Labeler to automate the categorization of release notes. Full disclosure: I'm the author of PR Labeler, but I think it could be very useful for users of Release Drafter which is the reason I created it :)
=> Add links to PR Labeler and Probot Auto Labeler

.vscode/launch.json
Allows you to press F5 and attach the debugger to `jest` making it easier to debug why a test would fail.
=> allow jest debugging with VSCode

README.md, index.js, lib/releases.js, test/fixtures/config/config-with-exclude-labels.yml, test/fixtures/config/config-with-excludes.yml, test/index.test.js
Adds the ability to exclude PRs from the changelog, based on their labels.
For example:
```yml
template: |
$CHANGES
categories:
- label: fix
title: 🐛 Bug Fixes
exclude-labels:
- dep-update
```
=> Add exclude-labels option for ignoring pull requests based on labels

test/fixtures/config/config-with-replacers.yml, test/fixtures/graphql-commits-merge-commit.json, test/fixtures/graphql-commits-rebase-merging.json, test/fixtures/graphql-commits-squash.json, test/index.test.js
I had manually adjusted some of the mocks which makes it difficult to maintain if we want to regenerate the mocks with added fields (e.g. for #188 we need to add the `mergedAt` field). I've now created a repo (https://github.com/TimonVS/release-drafter-test-repo) with three different branches (`merge-commit`, `rebase-merging` and `squash-merging`) which can be used to regenerate mocks if needed.
=> Update mocks to make them easier to maintain

README.md, index.js, lib/commits.js, lib/sort-pull-requests.js, test/fixtures/config/config-with-sort-direction-ascending.yml, test/fixtures/graphql-commits-paginated-1.json, test/fixtures/graphql-commits-paginated-2.json, test/index.test.js
This PR adds the `sort-direction` option. Valid values are `ascending` or `descending`. I do notice that the list of configuration options is getting quite long, we may want to split up more advanced configuration options like this one into another document in the near future.
Fixes: #188
=> Add `sort-direction` option

README.md, lib/template.js, test/fixtures/config/config-with-replacers.yml, test/template.test.js
In #185 we added a new `replacers` option, that had two separate sub-keys: `regex` and `search`. This simplifies the config down to a single `search` key that can handle both plain string values, and strings that look like a regular expression.
The `regex` key can no longer be used.
=> Remove ‘regex’ key from the ‘search’ option

index.js, test/index.test.js
For some reason unbenkownst to me, Github Actions payload refs are different to the usual webhooks.
For example:
> 22:49:29.286Z  INFO probot: toolmantim/release-drafter: Ignoring push. renovate/semver-6.x is not one of: master
This changes it to use the `GITHUB_REF` environment variable.
=> Fix branch matching for GitHub Actions

lib/commits.js
I made a mistake in #224 because new PRs from me and @casz aren't showing up in the release notes draft. I will take another look at fixing this for real this week.
=> Don't filter cross repository PRs

README.md
The second version of GitHub Actions, ["now with world-class CI/CD"](https://github.com/features/actions), was [announced on 2019-08-08](https://www.youtube.com/watch?v=E1OunoCyuhY). It is now in public beta and is slated for general availability to all users very soon on 2019-11-13.
As part of this upgrade, the original version of GitHub Actions workflows and its HCL-like syntax are also considered deprecated and support for them will be removed in the near future.
As such, it would be best to feature the new YAML workflow syntax in your Action's README example! 🎉 
---
If you don't like how any part of this reads, feel free to edit it directly. 👌
=> Add GitHub Actions V2 workflow example

README.md, index.js, lib/sort-pull-requests.js, test/fixtures/config/config-with-sort-by-title.yml, test/index.test.js
Closes #323
This PR adds the `sort-by` option for users to be able to sort changelogs by `merged_at` or `title`.
=> Add a `sort-by` option

README.md, docs/github-app.md
Move the usage doc for the Release Drafter GitHub App to a separate doc to make it less prominent and stimulate the use of the GitHub Action.
Related to https://github.com/release-drafter/release-drafter/issues/335
=> Move GitHub App usage doc out of README to separate doc

README.md, index.js, lib/config.js
Fixes: https://github.com/release-drafter/release-drafter/issues/332
Allows marking the draft as pre-release when it is created, throught the `prerelease` config option.
=> Add "prerelease" config option

index.js
Set tag name in `updateRelease` parameters to keep GitHub from resetting the tag to `untagged-<hash>`.
Fixes: https://github.com/release-drafter/release-drafter/issues/204
=> Prevent untagged-<hash> being set as tag name

README.md, index.js, lib/config.js, test/fixtures/config/config-name-input.yml, test/helpers/config-mock.js, test/index.test.js
This is useful if you want to create different drafts, depending on the triggered workflow.
You may want to create a pre-release draft in the development branch (targeting this branch) and have a `-alpha` suffix in the tag-template and, separately, create a release draft in the master branch (targeting it), without the suffix in the tag-template and maybe other different options.
So, in the workflow we can pass a different config name as an env variable when using release-drafter.
=> Allow specifying the config name through an input option

package.json
This updates the deploy script to use Heroku instead of Zeit's Now, now that their v1 platform has stopped deploying the application with an unknown error.
=> Deploy to Heroku on release

index.js
Updates to an existing draft were failing if the existing draft didn't have a tag name set. I added a check for `tag_name` on the existing draft, if it doesn't exist we don't set it instead of setting it to `null` (which is the value of `tag_name` in the previous draft if no tag name was set).
=> Fix draft update from failing

README.md, index.js, lib/releases.js, lib/template.js, lib/versions.js, package.json, test/fixtures/config/config-with-input-version-template.yml, test/fixtures/config/config-with-resolved-version-template.yml, test/index.test.js, yarn.lock
Allow overriding the resulting version, tag and name throught input options.
This is useful for workflows scoped by branches (https://github.com/release-drafter/release-drafter/pull/359) that need to transition a version from one branch to another - GitFlow, for example.
=> Override calculated version, tag and name with input

index.js, lib/releases.js
Fixes the issue described here: https://github.com/release-drafter/release-drafter/pull/363#issuecomment-576886932
After thinking about it I don't think we should provide a config option for it. If you opt-in to having Release Drafter generate version numbers, you can expect it to override the tag and the release name. I consider not doing so as a bug.
=> Update name and tag name in draft updates

README.md, lib/default-config.js, lib/releases.js, lib/schema.js, schema.json, test/fixtures/config/config-with-include-labels.yml, test/index.test.js
Adding feature discussed in: https://github.com/release-drafter/release-drafter/issues/499
Note, feature has not been agreed upon yet. Consider this WIP until feature has consensus.
fixes #499
=> Add include-labels option

README.md
Per the conversation in #424, this PR takes a stab at adding an `Action Inputs` section to the README 🙂
=> Document GitHub action inputs

README.md, bin/generate-fixtures.js, index.js, lib/commits.js, lib/releases.js, test/fixtures/__generated__/graphql-commits-merge-commit.json, test/fixtures/__generated__/graphql-commits-overlapping-label.json, test/fixtures/__generated__/graphql-commits-rebase-merging.json, test/fixtures/__generated__/graphql-commits-squash-merging.json, test/fixtures/config/config-with-changes-templates-and-body.yml, test/index.test.js
We make extensive use of the pull request body and automatically send out the release body to a group of people when the release is deployed.
As such I would like to stop having to copy the PR body manually into the release notes. 
I have added a test however it is not very good because I think I need to be a PR in this [repo]( https://github.com/TimonVS/release-drafter-test-repo) with a body to do a proper test. If there is a way to get that or another way to add a test body please do let me know.
fixes #517
=> Allow adding the body of the PR to the release

README.md, index.js
This is necessary if you are planning to execute additional steps after creating the release draft. As the release name and tag are autogenerated, it is essential that the action provides these.
=> Set the release name and tag_name as outputs of the action

.github/release-drafter.yml, .github/workflows/draft.yml
yup, let's use version resolver to get correct version numbers, means less work when releasing 😆
Once all issues are fixed, I can envision an automated release when a tag is pushed!
=> dog food release-drafter

README.md
The configuration example in `README.md` has a `version-resolver` section with labels that supposed to control the version name / tag strings. However, this example dos not work out of the box, which could be frustrating, especially for new users.
This tiny PR is to update name/tag templates with `$RESOLVED_VERSION`, so the version labels, if present, will actually be used.
=> Update example in README to use version resolution

README.md, bin/generate-fixtures.js, lib/commits.js, lib/releases.js, test/fixtures/__generated__/graphql-commits-forking.json, test/fixtures/__generated__/graphql-commits-merge-commit.json, test/fixtures/__generated__/graphql-commits-overlapping-label.json, test/fixtures/__generated__/graphql-commits-rebase-merging.json, test/fixtures/__generated__/graphql-commits-squash-merging.json, test/fixtures/config/config-with-changes-templates-and-url.yml, test/index.test.js
We are actively uses a repo's release notes in scope of other repos.  
This makes a github PR's short link (`#NUMBER`) lead to a wrong place.
So I would like to have an option to use an issue's complete URL instead of hardcoded replacements.
=> Allow adding the URL of the PR to the release notes

bin/generate-schema.js, schema.json
The schema was containing an empty array for the required field, which is incompatible with the draft 04 specification.
I hesitated to simply remove the field as technically we are currently filtering a list containing a single element, however I fear it's error prone for the future.
Tell me if the js code is wrong, js is not really my strong suit, happy :)
=> Make the generated schema compliant with draft04

index.js, lib/releases.js
Consider only releases targeting the same branch as the branch being used for the drafting the new release.
Releases that are for other branches will not be considered for the calculation for the changes.
This also possibly addresses #656
=> filter releases to consider only the target branch 

README.md
As all new projects are using main instead of default we make use of github macro in order to have an example that works regardless which is current default branch.
See https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/ for details.
=> Improve example to use default branch

README.md, index.js, lib/default-config.js, lib/releases.js, lib/schema.js, schema.json
Filter releases to consider only the target branch, this time by enabling a config option named `filter-by-commitish`.
The default is `false` so previous behaviour is unchanged.
Should fix the breaking changes of #657
=> Filter releases to consider only the target branch

index.js
We would like to propose a change, where it is the github action determines, when a release-drafter should be run.
We have a usecase, where it is a workflow dispatch event, that triggers the action and this line: ```app.on('push', async (context) => {``` prevents the action to run. 
Maybe there is a better way to solve this problem rather than replacing ```push``` with ```*```. Your input is welcome.
=> Allow more than just a push event to run the action

.prettierrc, README.md, lib/default-config.js, lib/releases.js, lib/schema.js, schema.json, test/schema.test.js
I wanted to avoid the hard-coded category title markdown, i.e. change it from `## Features` to `### Features` to be a bit more subtle.
=> Category templating

Dockerfile, index.js
Github Enterprise doesn't have official Action support yet and the release-drafter needs still to be run in GITHUB_APP mode:
- Fix the Docker entrypoint to actually run without errors
- Avoid creating any Actions output, if we aren't in Actions mode
- Add a healthcheck endpoint for Kubernetes deployments in Github App mode
=> Container compatibility

README.md, index.js, lib/default-config.js, lib/schema.js, lib/template.js, package.json, schema.json, yarn.lock
As release-drafter is catogorizing releases notes based on labels, it's nice to integrate optional labeling support as well. Check the README for configuration.
=> Add autolabeler

README.md
the example snippet can't be copy/pasted as is because it uses invalid syntax.
=> Fix syntax on example snippet

README.md, action.yml, index.js
The main motivation here is to have some control which events are dispatched to the actual "releaser" code as it gets processed with every event now: configuring the release-drafter for `pull_request` only, makes it generate draft releases as well.
This can now be controlled via action inputs for both "releaser" and "autolabeler" independently and both functionalities are enabled by default.
=> Configurable functionality

README.md
Documentation added in https://github.com/release-drafter/release-drafter/pull/774 is not explicit how multiple matchers are handled in the code
=> Clarify how autolabeler matcher configurations work

lib/versions.js, test/fixtures/config/config-with-major-minor-patch-version-template.yml, test/fixtures/config/config-with-major-minor-version-template.yml, test/fixtures/config/config-with-major-version-template.yml, test/fixtures/config/config-with-next-versioning.yml, test/index.test.js, test/versions.test.js
In our use case just having the full version string available in the template isn't enough.
E.g. `$NEXT_MINOR_VERSION` will render the full e.g. `2.8.0`, but want to render headings that just contain "2.8" (Like "What's new in Play 2.8?", but more importantly we have links to our docs that look like
- https://www.playframework.com/documentation/2.8.x/Home
- https://www.playframework.com/documentation/2.8.x/Migration28
So we need to be able to render versions like "2.8.x" or just "28".
With this PR we can do this via: "`$NEXT_MINOR_VERSION_MAJOR.$NEXT_MINOR_VERSION_MINOR.x`" and "`$NEXT_MINOR_VERSION_MAJOR$NEXT_MINOR_VERSION_MINOR`"
=> Add $NEXT_{PATCH,MINOR,MAJOR}_VERSION_{PATCH,MINOR,MAJOR} variables

CONTRIBUTING.md, index.js
One of the input for the autolabeler is the PR title. If while creating the PR, the title didn't conform with any of the autolabeling rules, changing afterwards does not trigger the autolabeler. 
- Include the `edited` event of pull requests.
=> Include `edited` event for autolabeler

index.js, lib/releases.js
The commitish parameter was previously ignored from action inputs and only read from the static config.yml, when the Readme and action.yml advertised the parameter as action inputs.
Fix by @MariuszKogut
Fixes #824
=> Use commitish from action inputs. Fixes #824.

README.md, lib/versions.js, test/versions.test.js
Currently if the version is a prerelease the prerelease string is discarded because `semver.coerce` discards it.
With this PR we now use `semver.parse` instead and fall back to coerce.
It also updates `splitSemVer` to always return a string instead of sometimes a `SemVer` instance (which currently becomes a string in `template` due to it having a `toString`) and sometimes string.
Finally it adds a `$COMPELTE` variable that can be used to access the full version string, otherwise it's still not possible to get the prerelease info in the template.
=> Fix prerelease string getting removed and add $COMPLETE version variable

lib/config.js, test/config.test.js
Added the following messages to the error when an invalid configuration file:
1. This message will also be output if the configuration file is not found
2. configuration file must reside in your default branch
~~I wanted to add a message for when a config file was not found, but it was difficult due to its structure, so I decided not to.~~ fixed
~~Two failure tests in  config.test.js, but that is unrelated to this fix.~~ fixed
=> Mod error message when invalid config

lib/schema.js, package.json, test/fixtures/config/config-with-custom-version-resolver-partial.yml, test/index.test.js, yarn.lock
=> ensure deep merge of config

bin/generate-fixtures.js, lib/commits.js, package.json, test/fixtures/__generated__/graphql-commits-forking.json, test/fixtures/__generated__/graphql-commits-merge-commit.json, test/fixtures/__generated__/graphql-commits-overlapping-label.json, test/fixtures/__generated__/graphql-commits-rebase-merging.json, test/fixtures/__generated__/graphql-commits-squash-merging.json, test/fixtures/graphql-commits-paginated-1.json, test/fixtures/graphql-commits-paginated-2.json, yarn.lock
=> ensure PRs are merged

lib/releases.js, lib/schema.js, lib/template.js, test/fixtures/config/config-with-categories-with-other-category.yml, test/index.test.js, test/schema.test.js
fixes #139
fixes #551
👏 Finally adding support for moving the categorized group
=> add support for moving uncategorized to a category with no labels

.github/release-drafter.yml, README.md, index.js, lib/releases.js, test/fixtures/config/config-with-compare-link.yml, test/index.test.js
=> add owner and repository context to template variables

lib/releases.js, test/fixtures/config/config-with-name-and-tag-template.yml, test/index.test.js
=> Expand vars in tag and name inputs

README.md, lib/releases.js, lib/schema.js, schema.json, test/fixtures/config/config-with-footer-template.yml, test/fixtures/config/config-with-header-and-footer-no-nl-no-space-template.yml, test/fixtures/config/config-with-header-and-footer-template.yml, test/fixtures/config/config-with-header-template.yml, test/index.test.js, test/schema.test.js
=> Add header and footer

lib/releases.js
Following https://github.com/release-drafter/release-drafter/pull/865#issuecomment-899041540 - indeed the existing release doesn't get updated, so this PR fixes that.
=> Update `target_commitish` when updating a release

lib/releases.js
GitHub API currently returns a 500 HTTP response if you attempt to fetch over 1000 releases.
This addresses the issue outlined at https://github.com/release-drafter/release-drafter/issues/1082
fixes #1082
=> Cap evaluated release limit at 1000

bin/generate-fixtures.js, lib/commits.js, lib/default-config.js, lib/schema.js, test/fixtures/__generated__/README.md, test/fixtures/__generated__/graphql-include-null-path-forking.json, test/fixtures/__generated__/graphql-include-null-path-merge-commit.json, test/fixtures/__generated__/graphql-include-null-path-overlapping-label.json, test/fixtures/__generated__/graphql-include-null-path-rebase-merging.json, test/fixtures/__generated__/graphql-include-null-path-squash-merging.json, test/fixtures/__generated__/graphql-include-path-src-5.md-forking.json, test/fixtures/__generated__/graphql-include-path-src-5.md-merge-commit.json, test/fixtures/__generated__/graphql-include-path-src-5.md-overlapping-label.json, test/fixtures/__generated__/graphql-include-path-src-5.md-rebase-merging.json, test/fixtures/__generated__/graphql-include-path-src-5.md-squash-merging.json, test/fixtures/config/config-with-include-paths.yml, test/index.test.js
---
This introduces a new GraphQL query, requesting all node IDs that contain modifications to the specified file list. That node list is then used to filter the full set of PRs to only the set that contain those node IDs, thus giving us only the PRs that include changes to our paths.
Examples of `include-paths`:
```yaml
- src/main
- README.md
- doc/
```
For a project with ancillary files that need not be considered for a release (an automated job that regenerates binary files on an automated basis, generating lots of noise, for example).
In my case, this is because I have many parallel instances of release-drafter, each running with different configurations, to release different binary artifacts from a single source tree. The project is organized this way for ease of contribution, as …
=> include-paths: Permit filtering only PRs that modify path prefixes

lib/releases.js
Fixes the problem from https://github.com/release-drafter/release-drafter/pull/1065#issuecomment-1049911908
@robbinjanssen appreciate if you could test this!
=> Filter by `commitish` regardless of the `refs/heads` prefix

README.md, index.js, lib/default-config.js, lib/releases.js, lib/schema.js, lib/versions.js, schema.json, test/fixtures/config/config-with-tag-prefix.yml, test/index.test.js
Extending #1084 with the rest of #935
- Include a configuration option to filter the draft tag by a static string prefix
A benefit of this is that if you use a `tag-template: v$RESOLVED_VERSION` and `tag-prefix: v`, prerelease versioning will be supported
=> Tag prefix

README.md, lib/releases.js, lib/schema.js, schema.json, test/fixtures/config/config-with-categories-with-collapse-after.yml, test/fixtures/config/config-with-categories-with-collapse.yml, test/index.test.js, test/releases.test.js
This implements a new feature as discussed in #1093 
Add the `collapse-after` integer to a category to make it hide the PRs if there are more than the given int.
=> Add a `collapse-after` option for categories

README.md
Hi,
README introduces that permission required by pull-requests should be write when to add label to PR.
`pull-requests: write  # for release-drafter/release-drafter to add label to PR`
I think this comment can mislead some users to think they can remove this option, if they don't need add label functionality.
After remove this option. release-drafter complains about permissions. (related  [issue](https://github.com/release-drafter/release-drafter/issues/869))
So I suggest to add more information about permission. 
which introduces write permission is optional for autolabeler and read permission is required at least.
Thanks.
=> Add more comments about pull requests permission

action.yml
Providing header or footer leads to a warning and the inputs are ignored
by the action. These two inputs are explicitly mentioned at
https://github.com/release-drafter/release-drafter#action-inputs. This
patch fixes the behavior to finally comply with the docs.
=> Add missing inputs to action config

lib/commits.js
* we are using your great action in a setup with quite a lot of labels (one repository with multiple teams using [prow](https://github.com/kubernetes/test-infra/tree/master/prow))
* some PRs are not drafted as only the first 10 labels of each PR are fetched
* fetch more labels of the pull requests in question
>Note: I am unsure what might be a good number (our setup normally comes with 10-20 labels). Would 100 be a performance issue?
Thanks in advance!
<sub>Mathias Zeller <mathias.zeller@mercedes-benz.com> Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>
=> fetch 100 labels for pull requests instead of 10

lib/releases.js
Also disregards pre-releases in addition to drafts when drafting.
Fixes: #1135
=> Only use last full release when drafting

lib/releases.js, test/releases.test.js
In documentation, it says 
> A known prefix used to filter release tags. For matching tags, this prefix is stripped before attempting to parse the version. Default: ""
However, while sorting version to retrieve the latest release, the prefix is taking into account and leads to sort regarding `created_at`, not semver
=> fix(release): strip prefix before comparing version

lib/releases.js, test/releases.test.js
Do **not** update *final* release drafts with when drafting a *prerelease* and vice versa
Given the following releases:
Name | Draft | Prerelease
-- | -- | --
v3.4.0 |   |  
v3.5.0-rc.4 |   | ✅
v3.5.0 | ✅  |  
v3.5.0-rc.5 | ✅ | ✅
when running release-drafter with this config:
```
prerelease: true
prerelease-identifier: rc
```
I'd expect the draft of `v3.5.0-rc.5` to be updated instead of `v3.5.0`.
This allows me to maintain a draft for the next prerelease, listing the changes since the previous prerelease, and a draft for the next final release, listing the changes since the previous final release.
=> Update only drafts with the same prerelease status

README.md
in #1300 the following action outputs were added, but not added to the readme documentation: `resolved_version`, `major_version`, `minor_version` and `patch_version`
*(accidetally deleted my fork of this repo and that lead to the first instance of this PR (#1405)  getting closed, sorry)*
=> Document added action outputs introduced in #1300

lib/commits.js, lib/releases.js, test/fixtures/__generated__/graphql-commits-forking.json, test/fixtures/__generated__/graphql-commits-merge-commit.json, test/fixtures/__generated__/graphql-commits-overlapping-label.json, test/fixtures/__generated__/graphql-commits-rebase-merging.json, test/fixtures/__generated__/graphql-commits-squash-merging.json, test/releases.test.js
As noted in #60, bot accounts are currently being mis-mentioned, where
instead of linking through to `dependabot[bot]` it'll tag a user
`@dependabot` which isn't the same, and can result in unwanted
notifications.
To address this, we can retrieve the type of user that has authored a
Pull Request, looking at the `__typename` to determine if it's a `Bot`
or a `User` account, and provide a Markdown link to the Bot account's
app page.
Unfortunately this may result in a name such as:
@[dependabot[bot]](https://github.com/apps/dependabot)
But this is a better result than tagging the wrong account.
Closes #60.
=> Fix: Correctly mention bot accounts in release notes

README.md
Because terminology change it confuse why not working on new repositories.
Old one for backward compatibility.
https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/
=> Ensure support new default branch name

bin/generate-fixtures.js, lib/commits.js, lib/default-config.js, lib/schema.js, test/fixtures/config/config-with-pull-request-limit.yml, test/index.test.js, test/schema.test.js
Adds a configuration option to resolve the issue described in https://github.com/release-drafter/release-drafter/issues/1354, where long-lived PRs could cause others to be omitted from the release summary. This option allows users to increase the number of PRs the action searches when looking for a merged PR containing a given commit. The option is not required and defaults to 5 (the currently used value).
An alternate approach would be to simply increase the hard-coded limit in the existing query, although this could theoretically have an impact on API load for users not affected by the original issue.
=> Add config option for PR query limit
